#!/bin/sh

export GOHOOP_TOP=`pwd`
echo "GOHOOP_TOP=$GOHOOP_TOP"

export GOHOOP_BIN_PATH=$GOHOOP_TOP/output/bin
echo "GOHOOP_BIN_PATH=$GOHOOP_BIN_PATH"

export GOHOOP_LIB_PATH=$GOHOOP_TOP/output/lib
echo "GOHOOP_LIB_PATH=$GOHOOP_LIB_PATH"

export GOHOOP_INC_PATH=$GOHOOP_TOP/output/include
echo "GOHOOP_INC_PATH=$GOHOOP_INC_PATH"
