PRONAME:=logger
TARGET:=lib$(PRONAME)
PRE_DEFINED:= 
BUILD_PATH:=$(shell pwd)
INCLUDES:=$(BUILD_PATH)/inc \
	$(GOHOOP_TOP)/gutils/ini/inc

SRCDIRS:=$(BUILD_PATH)/src

LIBS_PATH:=

LIBS:=

SLIBS:=

include ../../static.mk
