PRONAME:=glogger
TARGET:=lib$(PRONAME)
PRE_DEFINED:= 
BUILD_PATH:=$(shell pwd)
INCLUDES:=$(BUILD_PATH)/inc \
	$(GOHOOP_TOP)/gutils/gxml/inc

SRCDIRS:=$(BUILD_PATH)/src

LIBS_PATH:=

LIBS:=

SLIBS:=$(GOHOOP_TOP)/gutils/gxml/output/lib/libgxml.a

include ../../static.mk
