PRONAME:=g_network_test
TARGET:=$(PRONAME)
PRE_DEFINED:= 
BUILD_PATH:=$(shell pwd)

INCLUDES:=$(GOHOOP_INC_PATH)

SRCDIRS:=$(BUILD_PATH)

LIBS_PATH:=$(GOHOOP_LIB_PATH)

LIBS:=gsystem gutils glogger gcommon

SLIBS:=

include $(GOHOOP_TOP)/app.mk