PRONAME:=g_network_test
VERSION:=1.0.0
TARGET:=$(PRONAME)
PRE_DEFINED:= 
BUILD_PATH:=$(shell pwd)

INCLUDES:=$(BUILD_PATH) \
    $(GOHOOP_INC_PATH)/gsystem \
    $(GOHOOP_INC_PATH)/gutils \
    $(GOHOOP_INC_PATH)/glogger \
    $(GOHOOP_INC_PATH)/gcommon

SRCDIRS:=$(BUILD_PATH)

LIBS_PATH:=$(GOHOOP_LIB_PATH)

LIBS:=gsystem gutils glogger gcommon

SLIBS:=

include $(GOHOOP_TOP)/app.mk