PRONAME:=gcommon
VERSION:=1.0.0
TARGET:=lib$(PRONAME)
PRE_DEFINED:= 
BUILD_PATH:=$(shell pwd)

INCLUDES:=

LIBS_PATH:= 

LIBS:= 

GCOMMON_PATH:=$(GOHOOP_TOP)/gcommon
SLIBS:= \
	$(GCOMMON_PATH)/component/conf/output/lib/libconf.a \
	$(GCOMMON_PATH)/component/filesys/output/lib/libfilesys.a \
	$(GCOMMON_PATH)/component/function/output/lib/libfunction.a \
	$(GCOMMON_PATH)/component/iostream/output/lib/libiostream.a \
	$(GCOMMON_PATH)/component/network/output/lib/libnetwork.a \
	$(GCOMMON_PATH)/system/output/lib/libsystem.a \

include ../../shared.mk
