all: tagini taglogger tagxml taglibmk

clean:
	$(MAKE) -C ini clean
	$(MAKE) -C logger clean
	$(MAKE) -C xml clean
	$(MAKE) -C libmk clean

cleanall:
	$(MAKE) -C ini cleanall
	$(MAKE) -C logger cleanall
	$(MAKE) -C xml cleanall
	$(MAKE) -C libmk cleanall

tagini:    
	$(MAKE) -C ini 

taglogger:	  
	$(MAKE) -C logger	

tagxml:    
	$(MAKE) -C xml 

taglibmk:    
	$(MAKE) -C libmk 
