PRONAME:=ini
VERSION:=1.0.0
TARGET:=lib$(PRONAME)
PRE_DEFINED:= 
BUILD_PATH:=$(shell pwd)
INCLUDES:=$(BUILD_PATH)/inc

SRCDIRS:= \
	$(BUILD_PATH)/src

LIBS_PATH:= 

LIBS:= 

SLIBS_PATH:= 

SLIBS:= 

include ../../static.mk
