PRONAME:=dnetwork
VERSION:= 1.0.0
TARGET:=lib$(PRONAME)
PRE_DEFINED:= 
BUILD_PATH:=$(shell pwd)

INCLUDES:=$(BUILD_PATH)/inc \
	      $(GOHOOP_TOP)/gcommon/inc

LIBS_PATH:= 

LIBS:= 

include ../../shared.mk
