PRONAME:=gutils
VERSION:=1.0.0
TARGET:=lib$(PRONAME)
PRE_DEFINED:= 
BUILD_PATH:=$(shell pwd)

INCLUDES:=

SLIBS:=../ini/output/lib/libini.a
	   ../logger/output/lib/liblogger.a
	   ../xml/output/lib/libxml.a

LIBS:=

LIBS_PATH:=

include ../../shared.mk
