PRONAME:=gini
TARGET:=lib$(PRONAME)
PRE_DEFINED:= 
BUILD_PATH:=$(shell pwd)

INCLUDES:=$(BUILD_PATH)/inc \
    $(GOHOOP_INC_PATH)/gsystem

SRCDIRS:=$(BUILD_PATH)/src

LIBS_PATH:=$(GOHOOP_LIB_PATH) 

LIBS:=gsystem

SLIBS:=

include $(GOHOOP_TOP)/static.mk
