PRONAME:=g_xml_test
TARGET:=$(PRONAME)
PRE_DEFINED:= 
BUILD_PATH:=$(shell pwd)

INCLUDES:=$(BUILD_PATH) \
    $(GOHOOP_INC_PATH)/gsystem \
    $(GOHOOP_INC_PATH)/gutils

SRCDIRS:=$(BUILD_PATH)

LIBS_PATH:=$(GOHOOP_LIB_PATH)

LIBS:=gutils gsystem

SLIBS:=

include $(GOHOOP_TOP)/app.mk
