all: gmaster gslave 

clean:
	$(MAKE) -C GMaster clean
	$(MAKE) -C GSlave clean

cleanall:
	$(MAKE) -C GMaster cleanall
	$(MAKE) -C GSlave cleanall

gmaster:
	$(MAKE) -C GMaster

gslave:
	$(MAKE) -C GSlave
