PRONAME:=component
TARGET:=lib$(PRONAME)
PRE_DEFINED:= 
BUILD_PATH:=$(shell pwd)
INCLUDES:=$(BUILD_PATH)/inc \

SRCDIRS:= \
	$(BUILD_PATH)/conf/src \
	$(BUILD_PATH)/filesys/src \
	$(BUILD_PATH)/function/src \
	$(BUILD_PATH)/iostream/src \
	$(BUILD_PATH)/network/src

LIBS_PATH:= 

LIBS:= 

SLIBS:= 

include ../../static.mk
