PRONAME:=logger_example
TARGET:=$(PRONAME)
PRE_DEFINED:= 
BUILD_PATH:=$(shell pwd)

INCLUDES:=$(GOHOOP_TOP)/gutils/logger/inc

SRCDIRS:=$(BUILD_PATH)

LIBS_PATH:=$(GOHOOP_TOP)/gutils/output/lib 

LIBS:=gutils

SLIBS:=

include ../../../app.mk
