PRONAME:=logger_example
TARGET:=$(PRONAME)
PRE_DEFINED:= 
BUILD_PATH:=$(shell pwd)

INCLUDES:=$(GOHOOP_TOP)/gutils/logger/inc

SRCDIRS:=$(BUILD_PATH)

LIBS_PATH:=$(GOHOOP_TOP)/gutils/output/lib \
	$(GOHOOP_TOP)/gcommon/output/lib

LIBS:=gutils gcommon pthread

SLIBS:=

include ../../../app.mk
