PRONAME:=filesys
TARGET:=lib$(PRONAME)
PRE_DEFINED:= 
BUILD_PATH:=$(shell pwd)
INCLUDES:=$(BUILD_PATH)/inc \
		  $(GOHOOP_TOP)/gcommon/inc

LIBS_PATH:= 

LIBS:= 

SLIBS_PATH:= 

SLIBS:= 

include ../../static.mk
